# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f88900c0c00d8d6d597651d7add1b45bcf74ae81544f8d9834be20b050764115120d9fb29487ea590aeb3f5565d66b521a892819d45a96c56a14ac15ee6f756

test:
  secret_key_base: 0714d9bb98d6f806ab4ed385493deca1c515048436aca00f56d838555c5602fafe19ab91d2405f856b017f495ce3a127254a95a225330858a00d907834ec980b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
